services:
  calculate:
    container_name: calculate
    build:
      context: ./
      dockerfile: ./Calculate/Dockerfile
    image: calculate:0.0.1
    ports:
      - '9090:9090'
    networks:
      - my-network


  deal:
    container_name: deal
    build:
      context: ./
      dockerfile: ./Deal/Dockerfile
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db/postgres
    image: deal:0.0.1
    ports:
      - '9091:9091'
    networks:
      - my-network


  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5433:5432'
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - my-network


networks:
  my-network:
    driver: bridge

volumes:
  db:
    driver: local
