server:
  port: 8080
feign:
  deal:
    url: http://localhost:9091
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: db/db.changelog-master.xml


---
spring:
  profiles:
    active: docker
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
  liquibase:
    enabled: true
    change-log: db/db.changelog-master.xml
feign:
  deal:
    url: http://deal:9091