spring:
  application:
    name: Calculate
server:
  error:
    include-message: always
    include-exception: true
  port: 9090
variables:
  baseRate: 0.2
  salaryPersent: 0.01
  insurancePersent: 0.03
  insuranceCost: 0.1
