spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
  mail:
    host: smtp.gmail.com
    port: 587
    username: "ustygovilya9@gmail.com"
    password: "obli dpvi upfa hrsh"
    default-encoding: UTF-8
    properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
              required: true
server:
  port: 8081



---
spring:
  profiles:
    active: docker
  kafka:
    consumer:
      bootstrap-servers: kafka1:9092
  mail:
    host: smtp.gmail.com
    port: 587
    username: "ustygovilya9@gmail.com"
    password: "obli dpvi upfa hrsh"
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
