spring:
  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_ADVERTISED_HOST_NAME_LOCAL}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USER}
    password: ${PASSWORD_USER}
    default-encoding: UTF-8
    properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
              required: true
server:
  port: 8081



---
spring:
  profiles:
    active: docker
  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_ADVERTISED_HOST_NAME_DOCKER}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USER}
    password: ${PASSWORD_USER}
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
