name: CI - Bank

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports:
          - "5433:5432"
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Show Java version
        run: java -version

      - name: Show Maven version
        run: mvn -version

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: Wait for PostgreSQL to start
        run: sleep 20

      - name: Build and Test Calculate Module and Analyze with SonarCloud
        run: |
          echo "Building and testing Calculate module"
          cd Calculate
          chmod +x mvnw
          ls -l mvnw
          pwd
          ./mvnw test -B -e
          ./mvnw sonar:sonar -Dsonar.organization=${{ env.SONAR_ORGANIZATION }} -Dsonar.projectKey=Ilya-IU_Bank-Calculate -Dspring.profiles.active=test

      - name: Build and Test Deal Module and Analyze with SonarCloud
        run: |
          echo "Building and testing Deal module"
          cd Deal
          chmod +x mvnw
          ls -l mvnw
          pwd
          ./mvnw test -B -e
          ./mvnw sonar:sonar -Dsonar.organization=${{ env.SONAR_ORGANIZATION }} -Dsonar.projectKey=Ilya-IU_Bank-Deal -Dspring.profiles.active=test

      - name: Build and Test Statement Module and Analyze with SonarCloud
        run: |
          echo "Building and testing Statement module"
          cd Statement
          chmod +x mvnw
          ls -l mvnw
          pwd
          ./mvnw test -B -e
          ./mvnw sonar:sonar -Dsonar.organization=${{ env.SONAR_ORGANIZATION }} -Dsonar.projectKey=Ilya-IU_Bank-Statement -Dspring.profiles.active=test

      - name: Build and Test Dossier Module and Analyze with SonarCloud
        run: |
          echo "Building and testing Dossier module"
          cd Dossier
          chmod +x mvnw
          ls -l mvnw
          pwd
          ./mvnw test -B -e
          ./mvnw sonar:sonar -Dsonar.organization=${{ env.SONAR_ORGANIZATION }} -Dsonar.projectKey=Ilya-IU_Bank-Dossier -Dspring.profiles.active=test

      - name: Build and Test GateAway Module and Analyze with SonarCloud
        run: |
          echo "Building and testing GateAway module"
          cd GateAway
          chmod +x mvnw
          ls -l mvnw
          pwd
          ./mvnw test -B -e
          ./mvnw sonar:sonar -Dsonar.organization=${{ env.SONAR_ORGANIZATION }} -Dsonar.projectKey=Ilya-IU_Bank-GateAway -Dspring.profiles.active=test

      - name: Generate Codecov Report
        run: bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}

