name: CI, SonarCloud Analysis and Codecov

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_and_analyze:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports:
          - "5433:5432"
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      JAVA_VERSION: 17
      SONAR_PROJECT_KEY: Ilya-IU_Bank
      SONAR_ORGANIZATION: ilya-iu
      MODULES: "Calculate Deal Statement Dossier GateAway"
      SONAR_HOST_URL: https://sonarcloud.io
      SONAR_LOGIN: ${{ secrets.SONAR_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Важно для Codecov и SonarCloud

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Show Java version
        run: java -version

      - name: Show Maven version
        run: mvn -version

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: Wait for PostgreSQL to start
        run: sleep 20

      - name: Build, Test, Analyze and Generate Reports
        run: |
          MODULES="Calculate Deal Statement Dossier GateAway"
          for MODULE in $MODULES; do
            echo "Building, testing and analyzing module: $MODULE"
            cd $MODULE
            chmod +x mvnw
            ls -l mvnw
            ./mvnw clean verify sonar:sonar \
              -Dsonar.projectKey=${{ env.SONAR_PROJECT_KEY }} \
              -Dsonar.organization=${{ env.SONAR_ORGANIZATION }} \
              -Dsonar.host.url=${{ env.SONAR_HOST_URL }} \
              -Dsonar.login=${{ env.SONAR_LOGIN }}
            cd ..
          done

      - name: Generate Codecov Report
        run: bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}